'use strict';
(() => {
const $=id=>document.getElementById(id), W=3734,H=5600,KEY='ad-atlas-state-v1',CLOUD=window.AD_CLOUD;
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLocaleLowerCase('ru').replace(/ё/g,'е').trim();
const clone=x=>JSON.parse(JSON.stringify(x));
const safeIcon=s=>typeof s==='string'&&/^(?:icons\/)?[a-zA-Z0-9_()\-]+\.png$/.test(s)?s.replace(/^icons\//,''):null;
const safePhoto=s=>CLOUD?.isAllowedPhoto(s)&&(!s.startsWith('data:')||s.length<=700000)?s:null;
let state,original,enabled=new Set(),editor=false,adding=false,selected=null,lastClick=null,tab='cats',toastTimer,markers=new Map(),undoStack=[],account=null,remoteStamp=null,saveQueue=Promise.resolve();
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500)}
function validate(input){
 const obj=Array.isArray(input)?{points:input,categoryMeta:{},categoryOrder:[]}:input;
 if(!obj||!Array.isArray(obj.points)||obj.points.length>20000)throw Error('Нужен JSON с массивом points (не более 20 000 точек).');
 const ids=new Set();const points=obj.points.map((p,i)=>{if(!p||typeof p!=='object'||typeof p.x!=='number'||typeof p.y!=='number'||!Number.isFinite(p.x)||!Number.isFinite(p.y)||p.x<0||p.x>W||p.y<0||p.y>H)throw Error(`У точки №${i+1} неверные координаты.`);let id=String(p.id??crypto.randomUUID());if(ids.has(id))id=crypto.randomUUID();ids.add(id);return {id,name:String(p.name??'').slice(0,200),desc:String(p.desc??'').slice(0,5000),category:String(p.category||'other').slice(0,150),icon:safeIcon(p.icon),photo:safePhoto(p.photo),x:p.x,y:p.y}});
 const categoryMeta=Object.create(null);if(obj.categoryMeta&&typeof obj.categoryMeta==='object'&&!Array.isArray(obj.categoryMeta))for(const [k,v] of Object.entries(obj.categoryMeta))categoryMeta[k]={title:String(v?.title||k).slice(0,150)};
 const categoryOrder=[...new Set([...(Array.isArray(obj.categoryOrder)?obj.categoryOrder.filter(x=>typeof x==='string'):[]),...Object.keys(categoryMeta),...points.map(p=>p.category)])];
 return {version:1,points,categoryMeta,categoryOrder};
}
try{original=validate(window.AD_DATA);state=clone(original);try{const local=localStorage.getItem(KEY);if(local){state=validate(JSON.parse(local));$('saveState').textContent='Ваши локальные правки'}}catch{toast('Не удалось прочитать локальные правки. Загружена исходная карта.')} }catch(e){$('loadError').hidden=false;$('loadError').textContent='Не удалось загрузить данные: '+e.message;return}
if(!window.L){$('loadError').hidden=false;$('loadError').textContent='Не загрузилась библиотека карты. Проверьте наличие папки vendor.';return}
state.categoryOrder.forEach(c=>enabled.add(c));
const map=L.map('map',{crs:L.CRS.Simple,minZoom:-5,maxZoom:3,zoomControl:false,attributionControl:true,zoomSnap:.25,preferCanvas:true});
const bounds=[[0,0],[H,W]];const overlay=L.imageOverlay('map.webp',bounds).addTo(map);overlay.on('load',()=>{$('mapStatus').textContent='Карта загружена'});overlay.on('error',()=>{$('loadError').hidden=false;$('loadError').textContent='Изображение карты не найдено. Проверьте файл map.webp.'});
map.fitBounds(bounds,{padding:[40,40]});map.setMaxBounds([[-H*.25,-W*.4],[H*1.25,W*1.4]]);map.options.maxBoundsViscosity=.8;
const layer=L.layerGroup().addTo(map);
const title=c=>state.categoryMeta[c]?.title||c;
const catIcon=c=>safeIcon(state.points.find(p=>p.category===c&&p.icon)?.icon);
function iconHTML(c){const src=catIcon(c);return src?`<img class="cat-icon" src="${esc(src)}" alt="" loading="lazy">`:'<span class="cat-dot" aria-hidden="true">◇</span>'}
function save(){try{localStorage.setItem(KEY,JSON.stringify(state))}catch{toast('Не удалось сохранить резервную копию в браузере.')}if(CLOUD&&account?.canEdit){const snapshot=clone(state);$('saveState').textContent='Сохранение…';saveQueue=saveQueue.catch(()=>{}).then(()=>CLOUD.saveState(snapshot)).then(row=>{remoteStamp=row?.updated_at||remoteStamp;$('saveState').textContent='Общая карта сохранена'}).catch(error=>{toast('Облако: '+error.message);$('saveState').textContent='Не удалось сохранить'})}else $('saveState').textContent=CLOUD?'Общая карта':'Локальная карта'}
function updateUndo(){const last=undoStack.at(-1);$('undo').disabled=!last;$('undoHint').textContent=last?`Можно отменить: ${last.label}`:'История действий пуста'}
function checkpoint(label){undoStack.push({label,state:clone(state),enabled:[...enabled],selected});if(undoStack.length>25)undoStack.shift();updateUndo()}
function undo(){const item=undoStack.pop();if(!item)return;state=item.state;enabled=new Set(item.enabled);selected=item.selected&&state.points.some(p=>p.id===item.selected)?item.selected:null;save();refresh();if(selected)showDetail(selected);else $('detail').hidden=true;setAdding(false);updateUndo();toast(`Отменено: ${item.label}`)}
function visible(){const q=norm($('search').value);return state.points.filter(p=>enabled.has(p.category)&&(!q||norm([p.name,p.desc,p.category,title(p.category)].join(' ')).includes(q)))}
function renderCategories(){
 const counts=new Map();state.points.forEach(p=>counts.set(p.category,(counts.get(p.category)||0)+1));
 $('catCount').textContent=state.categoryOrder.length;
 $('categories').innerHTML=state.categoryOrder.map((c,i)=>`<div class="category ${enabled.has(c)?'':'off'}"><label>${iconHTML(c)}<span class="cat-name">${esc(title(c))}</span><span class="cat-count">${counts.get(c)||0}</span><input type="checkbox" data-index="${i}" aria-label="${esc(title(c))}" ${enabled.has(c)?'checked':''}></label>${editor?`<button class="cat-edit" data-edit="${i}" aria-label="Изменить категорию ${esc(title(c))}">⋯</button>`:''}</div>`).join('');
 $('categories').querySelectorAll('input').forEach(el=>el.onchange=()=>{const c=state.categoryOrder[Number(el.dataset.index)];el.checked?enabled.add(c):enabled.delete(c);el.closest('.category').classList.toggle('off',!el.checked);renderPoints()});
 $('categories').querySelectorAll('[data-edit]').forEach(el=>el.onclick=()=>categoryDialog(state.categoryOrder[Number(el.dataset.edit)]));
}
function renderPoints(){
 const pts=visible();$('stats').textContent=`${pts.length} из ${state.points.length} точек`;$('pointCount').textContent=pts.length;
 layer.clearLayers();markers.clear();
 for(const p of pts){const icon=L.divIcon({className:'point-marker'+(selected===p.id?' selected':''),html:p.icon?`<img src="${esc(p.icon)}" alt="" draggable="false">`:'<span style="color:#b9f17b">◆</span>',iconSize:[30,30],iconAnchor:[15,15]});
 const marker=L.marker([p.y,p.x],{icon,draggable:editor,title:p.name||title(p.category),alt:p.name||title(p.category),riseOnHover:true}).addTo(layer);
 const tooltip=p.photo?`<div class="photo-tooltip"><img src="${esc(p.photo)}" alt="Скриншот локации"><strong>${esc(p.name||title(p.category))}</strong><span>${esc(title(p.category))}</span></div>`:esc(p.name||title(p.category));
 marker.bindTooltip(tooltip,{direction:'top',offset:[0,-16],className:p.photo?'photo-leaflet-tooltip':''});marker.on('click',()=>showDetail(p.id));
 marker.on('dragend',()=>{const ll=marker.getLatLng();checkpoint(`перемещение «${p.name||title(p.category)}»`);p.x=Math.round(Math.max(0,Math.min(W,ll.lng))*100)/100;p.y=Math.round(Math.max(0,Math.min(H,ll.lat))*100)/100;save();renderPoints();showDetail(p.id)});markers.set(p.id,marker);
 }
 $('results').innerHTML=pts.length?pts.map((p,i)=>`<button class="result" data-point="${i}">${iconHTML(p.category)}<div>${esc(p.name||title(p.category))}<small>${esc(title(p.category))} · ${Math.round(p.x)}, ${Math.round(p.y)}</small></div><span>↗</span></button>`).join(''):'<div class="empty">Ничего не найдено.<br>Измените запрос или включите нужные категории.</div>';
 $('results').querySelectorAll('[data-point]').forEach(el=>el.onclick=()=>{const p=pts[Number(el.dataset.point)];map.setView([p.y,p.x],Math.max(map.getZoom(),-1));showDetail(p.id);closeSidebar()});
 if(selected&&!pts.some(p=>p.id===selected)){selected=null;$('detail').hidden=true}
}
function refresh(){renderCategories();renderPoints()}
function updateAccountUI(){const canEdit=!!account?.canEdit;$('account').textContent=account?account.isOwner?'Кабинет владельца':'Личный кабинет':'Войти';$('editor').hidden=!canEdit;if(!canEdit&&editor){editor=false;$('editor').setAttribute('aria-pressed','false');$('editor').innerHTML='✎ <span>Редактор</span>';$('editTools').hidden=true;setAdding(false);refresh()}$('saveState').textContent=remoteStamp?'Общая карта':CLOUD?'Общая карта':'Локальная карта'}
async function applyRemote(remote){if(!remote?.data)return false;state=validate(remote.data);original=clone(state);enabled=new Set(state.categoryOrder);selected=null;remoteStamp=remote.updated_at||remoteStamp;try{localStorage.setItem(KEY,JSON.stringify(state))}catch{};$('detail').hidden=true;refresh();return true}
async function initializeCloud(){if(!CLOUD){$('saveState').textContent='Локальная карта';return}try{const [remote,user]=await Promise.all([CLOUD.loadState(),CLOUD.currentAccount().catch(()=>null)]);account=user;if(remote?.data)await applyRemote(remote);else if(account?.canEdit){const seeded=await CLOUD.saveState(state);remoteStamp=seeded?.updated_at||null}$('saveState').textContent='Общая карта';updateAccountUI();setInterval(async()=>{if(editor)return;try{const next=await CLOUD.loadState();if(next?.updated_at&&next.updated_at!==remoteStamp)await applyRemote(next)}catch{}},30000)}catch(error){updateAccountUI();$('saveState').textContent='Карта офлайн';toast('Облачная карта пока недоступна: '+error.message)}}
async function accountDialog(){if(!CLOUD){toast('Облачное подключение недоступно');return}if(!account){openDialog('Вход в редактор',`<p class="help-text">Просматривать карту можно без входа. Аккаунт нужен только для редактирования.</p><label class="field">Email<input id="loginEmail" type="email" autocomplete="email" required></label><label class="field">Пароль<input id="loginPassword" type="password" minlength="6" autocomplete="current-password" required></label><button id="registerAccount" type="button">Создать аккаунт</button><p class="auth-status" id="authStatus"></p>`,async()=>{try{account=await CLOUD.signIn($('loginEmail').value.trim(),$('loginPassword').value);updateAccountUI();const remote=await CLOUD.loadState();if(remote?.data)await applyRemote(remote);else if(account?.canEdit){const seeded=await CLOUD.saveState(state);remoteStamp=seeded?.updated_at||null}toast(account?.canEdit?'Вход выполнен':'Вход выполнен, но права редактора не выданы')}catch(error){$('authStatus').textContent=error.message;return false}},'Войти');$('registerAccount').onclick=async()=>{const email=$('loginEmail').value.trim(),password=$('loginPassword').value;if(!email||password.length<6){$('authStatus').textContent='Укажите email и пароль не короче 6 символов.';return}$('registerAccount').disabled=true;try{const result=await CLOUD.signUp(email,password);$('authStatus').textContent=result?.access_token?'Аккаунт создан. Теперь можно войти.':'Проверьте почту и подтвердите регистрацию, затем войдите.'}catch(error){$('authStatus').textContent=error.message}finally{$('registerAccount').disabled=false}};return}
 let editors=[];if(account.isOwner){try{editors=await CLOUD.listEditors()}catch(error){toast(error.message)}}openDialog('Личный кабинет',`<div class="account-card"><span class="account-badge">${account.isOwner?'Владелец':account.canEdit?'Редактор':'Просмотр'}</span><strong>${esc(account.user.email)}</strong></div>${account.isOwner?`<div class="editor-manager"><label class="field">Добавить редактора по email<input id="editorEmail" type="email" placeholder="name@example.com"></label><button class="primary" id="addEditorAccess" type="button">Добавить редактора</button><div class="editor-list">${editors.map(item=>`<div><span><b>${esc(item.email)}</b><small>${item.role==='owner'?'Владелец':item.enabled?'Редактор':'Доступ отключён'}</small></span>${item.role!=='owner'?`<button type="button" data-editor="${esc(item.email)}" data-enabled="${item.enabled}">${item.enabled?'Отключить':'Включить'}</button>`:''}</div>`).join('')}</div></div>`:''}<button id="signOut" class="danger" type="button">Выйти из аккаунта</button>`,null,'Закрыть');$('signOut').onclick=async()=>{await CLOUD.signOut();account=null;updateAccountUI();$('dialog').close();toast('Вы вышли из аккаунта')};if(account.isOwner){$('addEditorAccess').onclick=async()=>{const email=$('editorEmail').value.trim();if(!email){toast('Укажите email редактора');return}try{await CLOUD.addEditor(email);toast('Редактор добавлен');$('dialog').close();accountDialog()}catch(error){toast(error.message)}};$('dialogContent').querySelectorAll('[data-editor]').forEach(button=>button.onclick=async()=>{try{await CLOUD.setEditorEnabled(button.dataset.editor,button.dataset.enabled!=='true');$('dialog').close();accountDialog()}catch(error){toast(error.message)}})}}
function closeSidebar(){document.body.classList.remove('sidebar-open');$('menu').setAttribute('aria-expanded','false')}
function selectTab(t){tab=t;$('categories').hidden=t!=='cats';$('results').hidden=t!=='points';$('tab-cats').setAttribute('aria-selected',String(t==='cats'));$('tab-points').setAttribute('aria-selected',String(t==='points'));$('tab-cats').tabIndex=t==='cats'?0:-1;$('tab-points').tabIndex=t==='points'?0:-1}
function showPhoto(src,alt='Скриншот локации'){const photo=safePhoto(src);if(!photo)return;$('lightboxImage').src=photo;$('lightboxImage').alt=alt;$('photoLightbox').showModal()}
function showDetail(id){const p=state.points.find(x=>x.id===id);if(!p)return;markers.get(selected)?.getElement()?.classList.remove('selected');selected=id;markers.get(id)?.getElement()?.classList.add('selected');$('detail').hidden=false;
 $('detail').innerHTML=`<button class="close" id="closeDetail" aria-label="Закрыть карточку">×</button><span class="eyebrow">${esc(title(p.category))}</span><h2>${esc(p.name||title(p.category))}</h2>${p.photo?`<img id="detailPhoto" class="detail-photo" src="${esc(p.photo)}" alt="Скриншот локации ${esc(p.name||title(p.category))}" title="Открыть на весь экран" tabindex="0">`:''}${p.desc?`<p>${esc(p.desc)}</p>`:''}<div class="coordinates">X ${p.x.toFixed(1)} &nbsp; / &nbsp; Y ${p.y.toFixed(1)}</div><div class="actions"><button id="copyPoint">Координаты</button>${editor?'<button class="primary" id="editPoint">Изменить</button>':''}</div>`;
 if(p.photo){const open=()=>showPhoto(p.photo,`Скриншот локации ${p.name||title(p.category)}`);$('detailPhoto').onclick=open;$('detailPhoto').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}}
 $('closeDetail').onclick=()=>{markers.get(selected)?.getElement()?.classList.remove('selected');selected=null;$('detail').hidden=true};$('copyPoint').onclick=()=>copy(`X=${p.x.toFixed(2)} Y=${p.y.toFixed(2)}`);if(editor)$('editPoint').onclick=()=>pointDialog(p);
}
async function copy(text){try{await navigator.clipboard.writeText(text);toast('Координаты скопированы')}catch{openDialog('Координаты',`<label class="field">Выделите и скопируйте<input value="${esc(text)}" readonly></label>`,null,'Закрыть');$('dialogContent').querySelector('input').select()}}
function openDialog(name,html,onSubmit,label='Сохранить'){if($('dialog').open)$('dialog').close();$('dialog').onpaste=null;$('dialogTitle').textContent=name;$('dialogContent').innerHTML=html;$('submitDialog').textContent=label;$('submitDialog').disabled=false;$('dialogForm').onsubmit=async e=>{e.preventDefault();if(!onSubmit){$('dialog').close();return}$('submitDialog').disabled=true;try{if(await onSubmit()!==false)$('dialog').close()}catch(error){toast(error.message)}finally{$('submitDialog').disabled=false}};$('dialog').showModal()}
function compressPhoto(file){return new Promise((resolve,reject)=>{if(!file?.type?.startsWith('image/')){reject(Error('Выберите изображение PNG, JPG или WebP.'));return}if(file.size>12000000){reject(Error('Файл слишком большой. Максимум 12 МБ.'));return}const reader=new FileReader(),img=new Image();reader.onerror=()=>reject(Error('Не удалось прочитать файл.'));reader.onload=()=>{img.onload=()=>{try{const scale=Math.min(1,1100/img.naturalWidth,820/img.naturalHeight),w=Math.max(1,Math.round(img.naturalWidth*scale)),h=Math.max(1,Math.round(img.naturalHeight*scale)),canvas=document.createElement('canvas');canvas.width=w;canvas.height=h;const context=canvas.getContext('2d');if(!context)throw Error('Браузер не поддерживает обработку изображения.');context.drawImage(img,0,0,w,h);let data=canvas.toDataURL('image/webp',.78);if(data.length>650000)data=canvas.toDataURL('image/webp',.58);if(data.length>700000)reject(Error('Скриншот не удалось достаточно сжать. Обрежьте его или выберите меньший файл.'));else resolve(data)}catch(e){reject(e)}};img.onerror=()=>reject(Error('Не удалось прочитать изображение.'));img.src=String(reader.result)};reader.readAsDataURL(file)})}
function pointDialog(p){const isNew=!p.id;let pendingPhoto=safePhoto(p.photo);openDialog(isNew?'Новая точка':'Редактировать точку',`<label class="field">Название<input id="pName" maxlength="200" value="${esc(p.name||'')}" placeholder="Например, заброшенный бункер" required></label><label class="field">Категория<select id="pCat">${state.categoryOrder.map(c=>`<option value="${esc(c)}" ${c===p.category?'selected':''}>${esc(title(c))}</option>`).join('')}</select></label><label class="field">Описание<textarea id="pDesc" maxlength="5000" placeholder="Что здесь можно найти…">${esc(p.desc||'')}</textarea></label><div class="field"><span>Скриншот места</span><div class="photo-upload"><div class="photo-preview" id="photoPreview" tabindex="0"></div><div class="photo-controls"><label for="pPhoto">＋ Загрузить фото</label><input id="pPhoto" type="file" accept="image/png,image/jpeg,image/webp" hidden><button id="pastePhoto" type="button">Вставить из буфера</button><button id="removePhoto" type="button">Удалить фото</button></div><div class="photo-status" id="photoStatus">Выберите файл или вставьте скриншот через Ctrl+V.</div></div></div><div class="two-cols"><label class="field">Координата X<input type="number" id="pX" step="any" min="0" max="${W}" required value="${p.x}"></label><label class="field">Координата Y<input type="number" id="pY" step="any" min="0" max="${H}" required value="${p.y}"></label></div>${!isNew?'<button class="danger" id="deletePoint" type="button">Удалить точку</button>':''}`,async()=>{const category=$('pCat').value;if(!category){toast('Сначала добавьте категорию');return false}const name=$('pName').value.trim();if(!name){toast('Укажите название');return false}const id=p.id||crypto.randomUUID();if(account?.canEdit&&pendingPhoto?.startsWith('data:')){$('photoStatus').textContent='Загружаем фото в общую карту…';try{pendingPhoto=await CLOUD.uploadPhoto(id,pendingPhoto)}catch(error){$('photoStatus').textContent=error.message;return false}}checkpoint(isNew?'добавление точки':`изменение «${p.name||name}»`);const next={id,name,desc:$('pDesc').value.trim(),category,x:Number($('pX').value),y:Number($('pY').value),icon:category===p.category?p.icon:catIcon(category),photo:pendingPhoto};if(isNew)state.points.push(next);else state.points[state.points.findIndex(x=>x.id===p.id)]=next;enabled.add(category);$('search').value='';save();refresh();showDetail(next.id);toast(isNew?'Точка добавлена':'Точка сохранена')});
 const drawPhoto=()=>{const preview=$('photoPreview'),open=()=>showPhoto(pendingPhoto,`Скриншот локации ${$('pName').value||title(p.category)}`);preview.innerHTML=pendingPhoto?`<img src="${esc(pendingPhoto)}" alt="Предпросмотр"><div>Скриншот добавлен.<br>Нажмите на него для просмотра.</div>`:'<div>Скриншот ещё не добавлен.</div>';preview.classList.toggle('has-photo',!!pendingPhoto);preview.title=pendingPhoto?'Открыть на весь экран':'';preview.onclick=pendingPhoto?open:null;preview.onkeydown=pendingPhoto?e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();open()}}:null;$('removePhoto').hidden=!pendingPhoto};drawPhoto();
 const applyPhoto=async file=>{if(!file)return;$('photoStatus').textContent='Обрабатываем изображение…';$('submitDialog').disabled=true;try{pendingPhoto=await compressPhoto(file);drawPhoto();$('photoStatus').textContent='Фото готово. Нажмите «Сохранить».'}catch(err){$('photoStatus').textContent=err.message;toast(err.message)}finally{$('submitDialog').disabled=false}};
 $('pPhoto').onchange=async e=>{await applyPhoto(e.target.files[0]);e.target.value=''};
 $('dialog').onpaste=async e=>{const file=[...e.clipboardData.items].find(item=>item.type.startsWith('image/'))?.getAsFile();if(file){e.preventDefault();await applyPhoto(file)}};
 $('pastePhoto').onclick=async()=>{try{if(!navigator.clipboard?.read)throw Error('Нажмите Ctrl+V, чтобы вставить скриншот.');const items=await navigator.clipboard.read();for(const item of items){const type=item.types.find(t=>t.startsWith('image/'));if(type){await applyPhoto(await item.getType(type));return}}throw Error('В буфере обмена нет изображения.')}catch(err){$('photoStatus').textContent=err.message;toast(err.message)}};
 $('removePhoto').onclick=()=>{pendingPhoto=null;drawPhoto();$('photoStatus').textContent='Фото будет удалено после сохранения точки.'};
 if(!isNew)$('deletePoint').onclick=()=>{if(confirm('Удалить эту точку?')){checkpoint(`удаление «${p.name||title(p.category)}»`);state.points=state.points.filter(x=>x.id!==p.id);save();refresh();$('dialog').close();toast('Точка удалена')}};
}
function categoryDialog(c){const isNew=c==null;openDialog(isNew?'Новая категория':'Настроить категорию',`<label class="field">Название<input id="cTitle" maxlength="150" required value="${esc(isNew?'':title(c))}"></label>${!isNew?`<label class="field">Позиция в списке<input id="cPosition" type="number" min="1" max="${state.categoryOrder.length}" value="${state.categoryOrder.indexOf(c)+1}" required></label><button id="deleteCategory" class="danger" type="button">Удалить категорию</button><p class="help-text">Точки удалённой категории перейдут в «Прочее».</p>`:''}`,()=>{const name=$('cTitle').value.trim();if(!name){toast('Укажите название');return false}checkpoint(isNew?'добавление категории':`изменение категории «${title(c)}»`);if(isNew){c='custom_'+crypto.randomUUID();state.categoryOrder.push(c);enabled.add(c)}else{const pos=Number($('cPosition').value)-1;state.categoryOrder=state.categoryOrder.filter(x=>x!==c);state.categoryOrder.splice(pos,0,c)}Object.defineProperty(state.categoryMeta,c,{value:{title:name},writable:true,configurable:true,enumerable:true});save();refresh();if(selected)showDetail(selected);toast('Категория сохранена')});
 if(!isNew)$('deleteCategory').onclick=()=>{if(c==='other'){toast('Категорию «Прочее» нельзя удалить');return}if(confirm(`Удалить категорию «${title(c)}»? Точки останутся на карте.`)){checkpoint(`удаление категории «${title(c)}»`);state.points.forEach(p=>{if(p.category===c)p.category='other'});delete state.categoryMeta[c];state.categoryOrder=state.categoryOrder.filter(x=>x!==c);if(!state.categoryOrder.includes('other'))state.categoryOrder.push('other');state.categoryMeta.other={title:'Прочее'};enabled.delete(c);enabled.add('other');save();refresh();$('dialog').close();if(selected)showDetail(selected)}};
}
function setAdding(value){adding=value;$('addBanner').hidden=!value;document.querySelector('.map-wrap').classList.toggle('adding',value);if(value)closeSidebar()}
function download(name,text,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
$('search').oninput=()=>{if($('search').value)selectTab('points');renderPoints()};
$('tab-cats').onclick=()=>selectTab('cats');$('tab-points').onclick=()=>selectTab('points');document.querySelector('.tabs').onkeydown=e=>{if(['ArrowLeft','ArrowRight'].includes(e.key)){e.preventDefault();selectTab(tab==='cats'?'points':'cats');$(tab==='cats'?'tab-cats':'tab-points').focus()}};
$('all').onclick=()=>{state.categoryOrder.forEach(c=>enabled.add(c));refresh()};$('none').onclick=()=>{enabled.clear();refresh()};
$('account').onclick=accountDialog;
$('editor').onclick=()=>{editor=!editor;$('editor').setAttribute('aria-pressed',String(editor));$('editor').innerHTML=editor?'✓ <span>Готово</span>':'✎ <span>Редактор</span>';$('editTools').hidden=!editor;setAdding(false);refresh();if(selected)showDetail(selected);if(editor){document.body.classList.add('sidebar-open');$('menu').setAttribute('aria-expanded','true');toast('Редактор включён. Точки можно перетаскивать.')}};
$('undo').onclick=undo;$('addPoint').onclick=()=>{if(!state.categoryOrder.length){toast('Сначала добавьте категорию');return}setAdding(true)};$('cancelAdd').onclick=()=>setAdding(false);$('addCategory').onclick=()=>categoryDialog(null);
$('zoomIn').onclick=()=>map.zoomIn();$('zoomOut').onclick=()=>map.zoomOut();$('fit').onclick=()=>map.fitBounds(bounds,{padding:[40,40]});
$('fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen()}catch{toast('Полный экран недоступен в этом браузере')}};
$('menu').onclick=()=>{const open=document.body.classList.toggle('sidebar-open');$('menu').setAttribute('aria-expanded',String(open))};
map.on('mousemove',e=>{$('coords').textContent=`X ${e.latlng.lng.toFixed(0)} / Y ${e.latlng.lat.toFixed(0)}`});map.on('click',e=>{const x=+e.latlng.lng.toFixed(2),y=+e.latlng.lat.toFixed(2);if(x<0||x>W||y<0||y>H)return;lastClick={x,y};$('copyCoords').disabled=false;$('coords').textContent=`X ${x} / Y ${y}`;if(adding){setAdding(false);pointDialog({x,y,name:'',desc:'',category:state.categoryOrder.find(c=>enabled.has(c))||state.categoryOrder[0],icon:null})}else closeSidebar()});
$('copyCoords').onclick=()=>{if(lastClick)copy(`X=${lastClick.x} Y=${lastClick.y}`)};
$('closeDialog').onclick=$('cancelDialog').onclick=()=>$('dialog').close();$('dialog').onclick=e=>{if(e.target===$('dialog')){const r=$('dialog').getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)$('dialog').close()}};
$('photoLightbox').onclick=e=>{if(e.target===$('photoLightbox'))$('photoLightbox').close()};$('photoLightbox').onclose=()=>{$('lightboxImage').removeAttribute('src')};
$('export').onclick=()=>openDialog('Экспорт карты','<p class="help-text">Скачайте резервную копию общей карты со всеми точками, категориями и ссылками на фотографии.</p><label class="field">Формат<select id="exportFormat"><option value="json">Резервная копия — JSON</option><option value="js">Архивный файл — data.js</option></select></label>',()=>{const js=$('exportFormat').value==='js';download(js?'data.js':'ad-atlas-backup.json',js?'window.AD_DATA = '+JSON.stringify(state,null,2)+';\n':JSON.stringify(state,null,2),js?'text/javascript':'application/json');toast('Файл экспорта подготовлен')},'Скачать');
$('import').onclick=()=>$('importFile').click();$('importFile').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>15000000)throw Error('Файл слишком большой (максимум 15 МБ).');const raw=JSON.parse(await file.text());const input=validate(Array.isArray(raw)?{points:raw,categoryMeta:state.categoryMeta,categoryOrder:state.categoryOrder}:raw);if(confirm(`Импортировать ${input.points.length} точек? Текущие локальные правки будут заменены.`)){checkpoint('импорт карты');state=input;enabled=new Set(state.categoryOrder);selected=null;$('detail').hidden=true;$('search').value='';save();refresh();toast('Карта импортирована')}}catch(e){toast('Импорт отменён: '+e.message)}finally{$('importFile').value=''}};
$('reset').onclick=()=>{if(confirm('Удалить локальные правки и вернуть опубликованную карту? Сначала скачайте экспорт, если правки нужны.')){checkpoint('сброс правок');try{localStorage.removeItem(KEY)}catch{toast('Не удалось очистить сохранение');return}state=clone(original);enabled=new Set(state.categoryOrder);selected=null;$('detail').hidden=true;$('search').value='';$('saveState').textContent='Исходная карта';refresh();toast('Исходная карта восстановлена')}};
$('help').onclick=()=>openDialog('Как пользоваться картой','<div class="help-text"><p>Перетаскивайте карту и приближайте колёсиком мыши или двумя пальцами. Нажмите на точку, чтобы узнать подробности.</p><p><b>Поиск</b> учитывает названия, описания и русские названия категорий. Поиск действует только по включённым категориям.</p><p><b>Личный кабинет</b> нужен только редакторам. Посетители всегда видят актуальную общую карту без регистрации.</p><p><b>Редактор</b> позволяет добавлять точки, менять описания и категории, прикреплять скриншоты и перетаскивать маркеры. Кнопка «Отменить» или <b>Ctrl/⌘ + Z</b> возвращает последнее изменение. Сохранённые правки появляются у всех посетителей.</p><p><b>/</b> — поиск · <b>Esc</b> — отмена добавления и закрытие карточки.</p></div>',null,'Понятно');
window.addEventListener('keydown',e=>{const typing=/INPUT|TEXTAREA|SELECT/.test(document.activeElement.tagName);if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'&&editor&&!typing&&!$('dialog').open){e.preventDefault();undo()}if(e.key==='/'&&!typing&&!$('dialog').open){e.preventDefault();document.body.classList.add('sidebar-open');$('menu').setAttribute('aria-expanded','true');$('search').focus()}if(e.key==='Escape'){setAdding(false);if(!$('dialog').open){$('detail').hidden=true;markers.get(selected)?.getElement()?.classList.remove('selected');selected=null;closeSidebar()}}});
new ResizeObserver(()=>map.invalidateSize()).observe($('map'));
refresh();selectTab('cats');updateUndo();updateAccountUI();initializeCloud();
})();
