'use strict';
const canvas=document.getElementById('mapCanvas'),ctx=canvas.getContext('2d'),mapImage=document.getElementById('mapImage'),capture=document.getElementById('capture'),captureCanvas=document.getElementById('captureCanvas'),captureCtx=captureCanvas.getContext('2d',{willReadFrequently:true}),statusEl=document.getElementById('status'),arrow=document.getElementById('playerArrow');
const MAP_W=3734,MAP_H=5600,FIRST_POINT={x:485.45220947266,y:-1378.0570068359,z:29.284469604492};
let coords={...FIRST_POINT},mapPoint=worldToMap(coords.x,coords.y),heading=0,zoom=1.6,panelVisible=true,autoTrack=true,streamReady=false,cvReady=false,mapReady=false,mapScale=.34,mapMat,mapKeypoints,mapDescriptors,orb,matcher,lastGoodMatch=0,matchBusy=false;

function worldToMap(x,y){return{x:313+(x+4000)*(3090/8500),y:626+(8000-y)*(4500/12000)}}
function resizeCanvas(){const rect=canvas.getBoundingClientRect(),ratio=Math.min(2,devicePixelRatio||1);canvas.width=Math.max(1,Math.round(rect.width*ratio));canvas.height=Math.max(1,Math.round(rect.height*ratio));draw()}
function draw(){if(!mapReady)return;const sourceW=canvas.width*2.7/zoom,sourceH=canvas.height*2.7/zoom,sx=Math.max(0,Math.min(MAP_W-sourceW,mapPoint.x-sourceW/2)),sy=Math.max(0,Math.min(MAP_H-sourceH,mapPoint.y-sourceH/2));ctx.clearRect(0,0,canvas.width,canvas.height);ctx.drawImage(mapImage,sx,sy,sourceW,sourceH,0,0,canvas.width,canvas.height);arrow.style.transform=`translate(-50%,-50%) rotate(${heading}deg)`}
function updateCoordinates(value,source='буфер'){if(!Number.isFinite(value.x)||!Number.isFinite(value.y))return;coords=value;mapPoint=worldToMap(value.x,value.y);document.getElementById('xValue').textContent=value.x.toFixed(2);document.getElementById('yValue').textContent=value.y.toFixed(2);statusEl.textContent=`${source}: ${value.x.toFixed(1)}, ${value.y.toFixed(1)}`;arrow.classList.remove('lost');draw()}
function applyHomography(H,x,y){const h=H.data64F?.length?H.data64F:H.data32F,a=h[0]*x+h[1]*y+h[2],b=h[3]*x+h[4]*y+h[5],c=h[6]*x+h[7]*y+h[8];return{x:a/c,y:b/c}}
function initMatcher(){if(!cvReady||!mapReady||mapDescriptors)return;try{const temp=document.createElement('canvas');temp.width=Math.round(MAP_W*mapScale);temp.height=Math.round(MAP_H*mapScale);temp.getContext('2d').drawImage(mapImage,0,0,temp.width,temp.height);mapMat=cv.imread(temp);cv.cvtColor(mapMat,mapMat,cv.COLOR_RGBA2GRAY);cv.equalizeHist(mapMat,mapMat);mapKeypoints=new cv.KeyPointVector();mapDescriptors=new cv.Mat();orb=new cv.ORB();orb.detectAndCompute(mapMat,new cv.Mat(),mapKeypoints,mapDescriptors);matcher=new cv.BFMatcher(cv.NORM_HAMMING,true);statusEl.textContent=`Карта готова: ${mapKeypoints.size()} ориентиров`}catch(error){statusEl.textContent='OpenCV: '+error.message}}
async function startCapture(){try{const stream=await navigator.mediaDevices.getDisplayMedia({video:{frameRate:{ideal:6,max:10}},audio:false});capture.srcObject=stream;await capture.play();streamReady=true;statusEl.textContent='Окно FiveM найдено';setInterval(matchMinimap,900)}catch(error){statusEl.textContent='Не удалось захватить FiveM';arrow.classList.add('lost')}}
function matchMinimap(){if(!autoTrack||!streamReady||!cvReady||!mapDescriptors||matchBusy||!capture.videoWidth)return;matchBusy=true;let src,gray,keypoints,descriptors,matches,srcPts,dstPts,mask,H;try{const vw=capture.videoWidth,vh=capture.videoHeight,x=Math.round(vw*.014),y=Math.round(vh*.808),w=Math.round(vw*.145),h=Math.round(vh*.163);captureCanvas.width=300;captureCanvas.height=188;captureCtx.drawImage(capture,x,y,w,h,0,0,300,188);src=cv.imread(captureCanvas);gray=new cv.Mat();cv.cvtColor(src,gray,cv.COLOR_RGBA2GRAY);cv.equalizeHist(gray,gray);keypoints=new cv.KeyPointVector();descriptors=new cv.Mat();orb.detectAndCompute(gray,new cv.Mat(),keypoints,descriptors);if(descriptors.empty()||keypoints.size()<12)throw Error('мало ориентиров');matches=new cv.DMatchVector();matcher.match(descriptors,mapDescriptors,matches);const good=[];for(let i=0;i<matches.size();i++){const m=matches.get(i);if(m.distance<68)good.push(m)}good.sort((a,b)=>a.distance-b.distance);const selected=good.slice(0,90);if(selected.length<10)throw Error('карта не распознана');const srcData=[],dstData=[];for(const m of selected){const a=keypoints.get(m.queryIdx).pt,b=mapKeypoints.get(m.trainIdx).pt;srcData.push(a.x,a.y);dstData.push(b.x,b.y)}srcPts=cv.matFromArray(selected.length,1,cv.CV_32FC2,srcData);dstPts=cv.matFromArray(selected.length,1,cv.CV_32FC2,dstData);mask=new cv.Mat();H=cv.findHomography(srcPts,dstPts,cv.RANSAC,4,mask);let inliers=0;for(let i=0;i<mask.rows;i++)inliers+=mask.ucharPtr(i,0)[0]?1:0;if(H.empty()||inliers<7)throw Error('низкая точность');const center=applyHomography(H,150,105),north=applyHomography(H,150,55);const detected={x:center.x/mapScale,y:center.y/mapScale};if(detected.x<0||detected.x>MAP_W||detected.y<0||detected.y>MAP_H)throw Error('точка вне карты');mapPoint.x=mapPoint.x*.72+detected.x*.28;mapPoint.y=mapPoint.y*.72+detected.y*.28;heading=Math.atan2(north.x-center.x,-(north.y-center.y))*180/Math.PI;lastGoodMatch=Date.now();statusEl.textContent=`Авто: ${inliers} совпадений`;arrow.classList.remove('lost');draw()}catch(error){if(Date.now()-lastGoodMatch>4000){statusEl.textContent=`Поиск: ${error.message}`;arrow.classList.add('lost')}}finally{for(const item of [src,gray,keypoints,descriptors,matches,srcPts,dstPts,mask,H])item?.delete?.();matchBusy=false}}

mapImage.onload=()=>{mapReady=true;resizeCanvas();initMatcher()};window.addEventListener('resize',resizeCanvas);window.addEventListener('opencv-ready',()=>{cvReady=true;initMatcher()});setInterval(()=>{if(window.cv?.Mat&&!cvReady){cvReady=true;initMatcher()}},500);
window.atlas.onCoordinates(value=>updateCoordinates(value));window.atlas.onLockState(locked=>{document.getElementById('lockButton').textContent=locked?'🔓 Разблокировать (F9)':'🔒 Закрепить поверх игры (F9)'});window.atlas.onTogglePanel(()=>{panelVisible=!panelVisible;document.getElementById('panel').classList.toggle('hidden',!panelVisible)});
document.getElementById('settingsButton').onclick=()=>{panelVisible=!panelVisible;document.getElementById('panel').classList.toggle('hidden',!panelVisible)};document.getElementById('zoom').oninput=event=>{zoom=Number(event.target.value);draw()};document.getElementById('autoTrack').onchange=event=>autoTrack=event.target.checked;document.getElementById('lockButton').onclick=()=>window.atlas.setLock(true);document.getElementById('close').onclick=()=>window.atlas.close();document.getElementById('minimize').onclick=()=>window.atlas.minimize();
updateCoordinates(FIRST_POINT,'первая точка');startCapture();
